/**
 * Central mock datasets for UI development and student project demos.
 * Replace these exports with API responses when backend integration is ready.
 */
const mockSummary = {
  totalIncome: 8500,
  totalExpenses: 5200,
  netSavings: 3300,
  savingsRate: 38.8,
  healthScore: 76,
};
const mockCategoryBreakdown = [
  { name: "Food", value: 1200, color: "#0891B2" },
  { name: "Transport", value: 800, color: "#06B6D4" },
  { name: "Shopping", value: 950, color: "#22D3EE" },
  { name: "Bills", value: 1100, color: "#67E8F9" },
  { name: "Health", value: 450, color: "#A5F3FC" },
  { name: "Entertainment", value: 700, color: "#0E7490" },
];
const mockIncomeVsExpense = [
  { month: "May", income: 7800, expense: 5100 },
  { month: "Jun", income: 8200, expense: 4900 },
  { month: "Jul", income: 7500, expense: 5300 },
  { month: "Aug", income: 8800, expense: 5600 },
  { month: "Sep", income: 8100, expense: 4800 },
  { month: "Oct", income: 8500, expense: 5200 },
  { month: "Nov", income: 8900, expense: 5400 },
  { month: "Dec", income: 9200, expense: 6100 },
  { month: "Jan", income: 8400, expense: 5e3 },
  { month: "Feb", income: 8600, expense: 5300 },
  { month: "Mar", income: 8700, expense: 5100 },
  { month: "Apr", income: 8500, expense: 5200 },
];
const mockDailyTrend = Array.from({ length: 30 }, (_, index) => ({
  day: `${index + 1}`,
  // Keep this deterministic so charts remain stable across refreshes/tests.
  amount: 50 + ((index * 37) % 300),
}));
const mockExpenses = [
  {
    id: "1",
    title: "Grocery Shopping",
    amount: 85.5,
    category: "Food",
    categoryColor: "#0891B2",
    date: "2026-04-15",
    paymentMethod: "Card",
    notes: "Weekly groceries",
    isRecurring: false,
    userId: "1",
  },
  {
    id: "2",
    title: "Uber Ride",
    amount: 24,
    category: "Transport",
    categoryColor: "#06B6D4",
    date: "2026-04-14",
    paymentMethod: "UPI",
    isRecurring: false,
    userId: "1",
  },
  {
    id: "3",
    title: "Netflix Subscription",
    amount: 15.99,
    category: "Entertainment",
    categoryColor: "#0E7490",
    date: "2026-04-13",
    paymentMethod: "Card",
    isRecurring: true,
    userId: "1",
  },
  {
    id: "4",
    title: "Electricity Bill",
    amount: 120,
    category: "Bills",
    categoryColor: "#67E8F9",
    date: "2026-04-12",
    paymentMethod: "Bank Transfer",
    isRecurring: true,
    userId: "1",
  },
  {
    id: "5",
    title: "New Shoes",
    amount: 89.99,
    category: "Shopping",
    categoryColor: "#22D3EE",
    date: "2026-04-11",
    paymentMethod: "Card",
    isRecurring: false,
    userId: "1",
  },
  {
    id: "6",
    title: "Doctor Visit",
    amount: 150,
    category: "Health",
    categoryColor: "#A5F3FC",
    date: "2026-04-10",
    paymentMethod: "Card",
    isRecurring: false,
    userId: "1",
  },
];
const mockIncomes = [
  {
    id: "1",
    title: "Monthly Salary",
    amount: 6500,
    category: "Salary",
    source: "Salary",
    date: "2026-04-01",
    isRecurring: true,
    userId: "1",
  },
  {
    id: "2",
    title: "Freelance Project",
    amount: 1200,
    category: "Freelance",
    source: "Freelance",
    date: "2026-04-08",
    isRecurring: false,
    userId: "1",
  },
  {
    id: "3",
    title: "Stock Dividends",
    amount: 350,
    category: "Investment",
    source: "Investment",
    date: "2026-04-05",
    isRecurring: false,
    userId: "1",
  },
  {
    id: "4",
    title: "Gift from Family",
    amount: 450,
    category: "Gift",
    source: "Gift",
    date: "2026-04-12",
    isRecurring: false,
    userId: "1",
  },
];
const mockCategories = [
  {
    id: "1",
    name: "Food",
    type: "EXPENSE",
    colorCode: "#0891B2",
    icon: "\u{1F354}",
    monthlyBudgetLimit: 1500,
    isDefault: true,
  },
  {
    id: "2",
    name: "Transport",
    type: "EXPENSE",
    colorCode: "#06B6D4",
    icon: "\u{1F697}",
    monthlyBudgetLimit: 800,
    isDefault: true,
  },
  {
    id: "3",
    name: "Shopping",
    type: "EXPENSE",
    colorCode: "#22D3EE",
    icon: "\u{1F6CD}\uFE0F",
    monthlyBudgetLimit: 1e3,
    isDefault: true,
  },
  {
    id: "4",
    name: "Bills",
    type: "EXPENSE",
    colorCode: "#67E8F9",
    icon: "\u{1F4C4}",
    monthlyBudgetLimit: 1200,
    isDefault: true,
  },
  {
    id: "5",
    name: "Health",
    type: "EXPENSE",
    colorCode: "#A5F3FC",
    icon: "\u{1F48A}",
    monthlyBudgetLimit: 500,
    isDefault: true,
  },
  {
    id: "6",
    name: "Entertainment",
    type: "EXPENSE",
    colorCode: "#0E7490",
    icon: "\u{1F3AC}",
    monthlyBudgetLimit: 800,
    isDefault: true,
  },
  {
    id: "7",
    name: "Salary",
    type: "INCOME",
    colorCode: "#0891B2",
    icon: "\u{1F4B0}",
    isDefault: true,
  },
  {
    id: "8",
    name: "Investment",
    type: "INCOME",
    colorCode: "#06B6D4",
    icon: "\u{1F4C8}",
    isDefault: true,
  },
];
const mockBudgets = [
  {
    id: "1",
    categoryId: "1",
    categoryName: "Food",
    limitAmount: 1500,
    spentAmount: 1200,
    period: "MONTHLY",
    alertThreshold: 80,
    startDate: "2026-04-01",
    endDate: "2026-04-30",
    isActive: true,
  },
  {
    id: "2",
    categoryId: "2",
    categoryName: "Transport",
    limitAmount: 800,
    spentAmount: 450,
    period: "MONTHLY",
    alertThreshold: 80,
    startDate: "2026-04-01",
    endDate: "2026-04-30",
    isActive: true,
  },
  {
    id: "3",
    categoryId: "3",
    categoryName: "Shopping",
    limitAmount: 1e3,
    spentAmount: 950,
    period: "MONTHLY",
    alertThreshold: 80,
    startDate: "2026-04-01",
    endDate: "2026-04-30",
    isActive: true,
  },
  {
    id: "4",
    categoryId: "6",
    categoryName: "Entertainment",
    limitAmount: 800,
    spentAmount: 320,
    period: "MONTHLY",
    alertThreshold: 80,
    startDate: "2026-04-01",
    endDate: "2026-04-30",
    isActive: true,
  },
];
const mockRecurring = [
  {
    id: "1",
    title: "Netflix",
    amount: 15.99,
    type: "EXPENSE",
    category: "Entertainment",
    frequency: "Monthly",
    startDate: "2024-01-01",
    paymentMethod: "Card",
    nextDueDate: "2026-05-01",
    isActive: true,
  },
  {
    id: "2",
    title: "Gym Membership",
    amount: 49.99,
    type: "EXPENSE",
    category: "Health",
    frequency: "Monthly",
    startDate: "2024-03-15",
    paymentMethod: "Card",
    nextDueDate: "2026-05-15",
    isActive: true,
  },
  {
    id: "3",
    title: "Monthly Salary",
    amount: 6500,
    type: "INCOME",
    category: "Salary",
    frequency: "Monthly",
    startDate: "2024-01-01",
    nextDueDate: "2026-05-01",
    isActive: true,
  },
  {
    id: "4",
    title: "Rent",
    amount: 1800,
    type: "EXPENSE",
    category: "Bills",
    frequency: "Monthly",
    startDate: "2024-01-01",
    paymentMethod: "Bank Transfer",
    nextDueDate: "2026-05-01",
    isActive: true,
  },
];
const mockNotifications = [
  {
    id: "1",
    title: "Budget Alert",
    message: "Food budget has reached 80% of limit",
    severity: "WARNING",
    isRead: false,
    isAcknowledged: false,
    createdAt: "2026-04-16T10:00:00",
    linkTo: "/budgets",
  },
  {
    id: "2",
    title: "Budget Exceeded",
    message: "Shopping budget exceeded the monthly limit!",
    severity: "CRITICAL",
    isRead: false,
    isAcknowledged: false,
    createdAt: "2026-04-15T14:30:00",
    linkTo: "/budgets",
  },
  {
    id: "3",
    title: "Recurring Due",
    message: "Netflix subscription due tomorrow",
    severity: "INFO",
    isRead: true,
    isAcknowledged: false,
    createdAt: "2026-04-14T09:00:00",
    linkTo: "/recurring",
  },
  {
    id: "4",
    title: "Monthly Summary",
    message: "Your March financial summary is ready",
    severity: "INFO",
    isRead: true,
    isAcknowledged: true,
    createdAt: "2026-04-01T08:00:00",
    linkTo: "/analytics",
  },
];
const mockSavingsRateTrend = [
  { month: "May", rate: 32 },
  { month: "Jun", rate: 35 },
  { month: "Jul", rate: 29 },
  { month: "Aug", rate: 36 },
  { month: "Sep", rate: 41 },
  { month: "Oct", rate: 38 },
  { month: "Nov", rate: 39 },
  { month: "Dec", rate: 34 },
  { month: "Jan", rate: 40 },
  { month: "Feb", rate: 38 },
  { month: "Mar", rate: 41 },
  { month: "Apr", rate: 39 },
];
export {
  mockBudgets,
  mockCategories,
  mockCategoryBreakdown,
  mockDailyTrend,
  mockExpenses,
  mockIncomeVsExpense,
  mockIncomes,
  mockNotifications,
  mockRecurring,
  mockSavingsRateTrend,
  mockSummary,
};
